<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        new Promise( function(resolve, reject) {
            setTimeout(() => {
                throw new Error("Whoops!");
            }, 1000);
        }).catch(alert); //no here the error is generated not while the executor is running, but later. So the promise canâ€™t handle it.
    
    </script>
</body>
</html>